# Generated by cpp11: do not edit by hand

ols_mat_ <- function(y, x) {
  .Call(`_dummypackage_ols_mat_`, y, x)
}

ols_dbl_ <- function(y, x) {
  .Call(`_dummypackage_ols_dbl_`, y, x)
}

eigen_sym_mat <- function(x) {
  .Call(`_dummypackage_eigen_sym_mat`, x)
}

eigen_sym_dbl <- function(x) {
  .Call(`_dummypackage_eigen_sym_dbl`, x)
}

eigen_gen_mat <- function(x) {
  .Call(`_dummypackage_eigen_gen_mat`, x)
}

eigen_gen_mat_complex_wrapper <- function(x) {
  .Call(`_dummypackage_eigen_gen_mat_complex_wrapper`, x)
}

eigen_gen_dbl_complex_wrapper <- function(x) {
  .Call(`_dummypackage_eigen_gen_dbl_complex_wrapper`, x)
}

eigen_gen_no_wrapper <- function(x) {
  .Call(`_dummypackage_eigen_gen_no_wrapper`, x)
}

chol_mat <- function(x, type) {
  .Call(`_dummypackage_chol_mat`, x, type)
}

ols_qr_mat <- function(y, x, econ) {
  .Call(`_dummypackage_ols_qr_mat`, y, x, econ)
}

ols_qr_dbl <- function(y, x, econ) {
  .Call(`_dummypackage_ols_qr_dbl`, y, x, econ)
}

capm <- function(r, m, f) {
  .Call(`_dummypackage_capm`, r, m, f)
}

typedef_Col_double <- function(x) {
  .Call(`_dummypackage_typedef_Col_double`, x)
}

typedef_Col_int <- function(x) {
  .Call(`_dummypackage_typedef_Col_int`, x)
}

typedef_uvec <- function(x) {
  .Call(`_dummypackage_typedef_uvec`, x)
}

typedef_Mat_double <- function(x) {
  .Call(`_dummypackage_typedef_Mat_double`, x)
}

typedef_Mat_int <- function(x) {
  .Call(`_dummypackage_typedef_Mat_int`, x)
}

typedef_SpMat_double <- function(x) {
  .Call(`_dummypackage_typedef_SpMat_double`, x)
}

typedef_SpMat_int <- function(x) {
  .Call(`_dummypackage_typedef_SpMat_int`, x)
}
